### ISSUE TITLE
Cheatsheet for ubuntu 64 bits

### ISSUE THREAD

**Issue by johnfelipe** [DemocraciaEnRed/billtracker#55]
Please tell me how install it

**Comment by gvilarino** [comment]
@johnfelipe we don't provide installation support for specific user scenarios outside of what's listed under `README.md`. If you do find a way to run it in Ubuntu, provide a PR please. I'll close this following #54 and any other OS specific request you may make.

If you want our dedicated support, please contact our citizen success team at `speak@democraciaenred.org` and discuss a paid support plan.
